[package]
name = "game_runtime"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
mlua = {version = "0.10", features = ["lua52", "vendored"]}
lang = { path = "../lang" }
graphics = { path = "../graphics" }
utils = {path = "../utils"}
